// <auto-generated />
using System;
using AxisTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AxisTest.Migrations
{
    [DbContext(typeof(Program.AxisContext))]
    partial class AxisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23253.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AxisTest.Program+AxisModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("AxisModel", (string)null);
                });

            modelBuilder.Entity("AxisTest.Program+AxisModel", b =>
                {
                    b.OwnsMany("AxisTest.Program+Axes", "AxesCollection", b1 =>
                        {
                            b1.Property<int>("AxisModelId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<decimal?>("X")
                                .HasColumnType("decimal(10,8)")
                                .HasColumnName("x");

                            b1.Property<decimal?>("Y")
                                .HasColumnType("decimal(10,8)")
                                .HasColumnName("y");

                            b1.Property<decimal?>("Z")
                                .HasColumnType("decimal(10,8)")
                                .HasColumnName("z");

                            b1.HasKey("AxisModelId", "Id");

                            b1.ToTable("AxisModel");

                            b1.ToJson("AxesCollection");

                            b1.WithOwner()
                                .HasForeignKey("AxisModelId");
                        });

                    b.Navigation("AxesCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
